export const CONTAINER_PADDING = 4;
export const DEFAULT_WIDTH = 50;
export const KNOB_SIZE = 24;

export const INITIAL_ANIMATION_VALUE = 0;
export const FINAL_ANIMATION_VALUE = DEFAULT_WIDTH - KNOB_SIZE - (CONTAINER_PADDING * 2);
